import { getAllNoteByUser } from "@/app/actions/notes.action";
import { Note } from "@/components/note/DisplayNotes/DisplayAllNotes";
import { Metadata } from "next";
import Image from "next/image";
import React from "react";
export const metadata: Metadata = {
  title: "Archived Notes | MemoMind-Save anything!",
  description: "Generated by create next app",
};
const page = async () => {
  const notes: Note[] = await getAllNoteByUser();

  const archivedNotes = notes.filter((note) => note.isArchived);
  return (
    <div className="w-screen min-h-screen flex items-center justify-center flex-col px-2 py-2">
      {archivedNotes.length > 0 ? (
        archivedNotes.map((note) => (
          <div
            key={note._id}
            className="w-96 p-3 h-auto m-2 rounded-lg border-2 border-gray-500"
          >
            <h2>{note.title}</h2>
            <p>{note.content}</p>
            {note.file && (
              <Image
                src={note.file.toString()}
                alt={note.title}
                width="200"
                height={400}
              />
            )}
            <p>Is Pinned: {note.isPin ? "Yes" : "No"}</p>
            <p>{note.user.toString()}</p>
            <p>{note.slug}</p>
          </div>
        ))
      ) : (
        <p>No unpinned notes available.</p>
      )}
    </div>
  );
};

export default page;
