import React from "react";
import { Metadata } from "next";
import InputNotes from "@/components/note/Inputs/InputNotes";
import DisplayAllNotes from "@/components/note/DisplayNotes/DisplayAllNotes";
export const metadata: Metadata = {
  title: "Create a Note | MemoMind-Save anything!",
  description: "Generated by create next app",
};

const NotePage = () => {
  return (
    <section>
      <div className="flex items-center justify-center p-4 flex-col gap-4">
        <div>
          <InputNotes />
        </div>
        <div>
          <DisplayAllNotes />
        </div>
      </div>
    </section>
  );
};

export default NotePage;
