
import React from "react";
import Nav from "@/components/note/Nav";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create a Note | MemoMind-Save anything!",
  description: "Generated by create next app",
};


const NotePage = () => {
  return (
    <section>
      <Nav />
    </section>
  );
};

export default NotePage;
