import React from "react";
import { Metadata } from "next";
import InputNotes from "@/components/note/Inputs/InputNotes";
export const metadata: Metadata = {
  title: "Create a Note | MemoMind-Save anything!",
  description: "Generated by create next app",
};

const NotePage = () => {
  return (
    <section>
      <div className="flex items-center justify-center p-4">
        <InputNotes />
      </div>
    </section>
  );
};

export default NotePage;
